name: walld_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0  # Core Firebase
  firebase_auth: ^5.3.1  # Email/password auth
  cloud_firestore: ^5.4.4  # Metadata, tasks, org data
  firebase_storage: ^12.3.3  # Attachments
  window_manager: ^0.3.7 # Window positioning/sizing control
  screen_retriever: ^0.1.9  # or latest compatible

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
